<h1>Books list</h1>

<hr>

<nav aria-label="Page navigation" style="text-align: center">
    <ul class="pagination">
        <?php foreach ($pagination as $button) :?>
            <?php if ($button->current) : ?>
                <li class = "active"><a href="?page=<?=$button->page?>"><?=$button->text?></a></li>
                <?php elseif($button->page==='...'): ?>
                    <li class='disabled'><a href="#"><?=$button->text?></a></li>
                    <?php elseif($button->isActive) : ?>
                    <li><a href="?page=<?=$button->page?>"><?=$button->text?></a></li>
                    <?php else : ?>
                        <li class='disabled'><a href="#"><?=$button->text?></a></li>
            <?php endif;
        endforeach; ?>

    </ul>
</nav>

<div class="row">
    <?php foreach ($books as $book) : ?>
        <div class="col-md-3">
            <div class="thumbnail"  style="height:400px;">
<!--                todo - изменить для каждой книги отдельное фото-->
                <img class="img-responsive" src="https://flytothesky.ru/wp-content/uploads/2012/10/%D1%84%D0%BE%D1%82%D0%BE-%D0%B4%D0%BD%D1%8F15.jpg">
                <div class="caption">
                    <h3><?=$book->getTitle()?></h3>
                    <p><?=$book->getPrice()?></p>
<!--                    TODO - авторы DONE-->
                    <p>
                    <?php foreach ($book->getAuthors() as $author):?>
                    <?="'".$author->getFirstName()." ".$author->getLastName()."' "?>
                    <?php endforeach;?>
                    </p>
                    <p>
                        <a href="/book-<?=$book->getId()?>.html" class="btn btn-primary" role="button">Details</a>
                        <a href="/cart/add/<?=$book->getId()?>" class="btn btn-default" role="button">Add to cart</a>
                    </p>
                </div>
            </div>
        </div>

    <?php endforeach; ?>
</div>
<!-- TODO -текущая страница - выделить, не указывать все страницы DONE-->
<nav aria-label="Page navigation" style="text-align: center">
    <ul class="pagination">
        <?php foreach ($pagination as $button) :?>
            <?php if ($button->current) : ?>
                <li class = "active"><a href="?page=<?=$button->page?>"><?=$button->text?></a></li>
            <?php elseif($button->page==='...'): ?>
                <li class='disabled'><a href="#"><?=$button->text?></a></li>
            <?php elseif($button->isActive) : ?>
                <li><a href="?page=<?=$button->page?>"><?=$button->text?></a></li>
            <?php else : ?>
                <li class='disabled'><a href="#"><?=$button->text?></a></li>
            <?php endif;
        endforeach; ?>

    </ul>
</nav>

