<h1>Books list</h1>

<hr>

<nav aria-label="Page navigation" style="text-align: center">
    <ul class="pagination">
        <?php foreach ($pagination as $button) :
            if ($button->isActive) : ?>
                <li><a href="?page=<?=$button->page?>"><?=$button->text?></a></li>
            <?php else : ?>
                <li class='disabled'><a href="#"><?=$button->text?></a></li>
            <?php endif;
        endforeach; ?>

    </ul>
</nav>

<div class="row">
    <?php foreach ($books as $book) : ?>
        <div class="col-md-3">
            <div class="thumbnail"  style="height:400px;">
<!--                todo - изменить для каждой книги отдельное фото-->
                <img class="img-responsive" src="https://flytothesky.ru/wp-content/uploads/2012/10/%D1%84%D0%BE%D1%82%D0%BE-%D0%B4%D0%BD%D1%8F15.jpg">
                <div class="caption">
                    <h3><?=$book->getTitle()?></h3>
                    <p><?=$book->getPrice()?></p>
<!--                    TODO - авторы-->
                    <p>...authors...</p>
                    <p>
                        <a href="/book-<?=$book->getId()?>.html" class="btn btn-primary" role="button">Details</a>
                        <a href="/cart/add/<?=$book->getId()?>" class="btn btn-default" role="button">Add to cart</a>
                    </p>
                </div>
            </div>
        </div>

    <?php endforeach; ?>
</div>
<!-- TODO -текущая страница - выделить, не указывать все страницы-->
<nav aria-label="Page navigation" style="text-align: center">
    <ul class="pagination">
        <?php foreach ($pagination as $button) :
            if ($button->isActive ) : ?>
                <li><a href="?page=<?=$button->page?>" > <?=$button->text?></a></li>
            <?php else : ?>
                <li class='disabled'><a href="#"><?=$button->text?></a></li>
            <?php endif;
        endforeach; ?>

    </ul>
</nav>


<!--<table class="table table-striped" >-->
<!--    <thread>-->
<!--        <tr class="bg-warning">-->
<!--            <th>-->
<!--                ID-->
<!--            </th>-->
<!--            <th>Title</th>-->
<!--            <th>Description</th>-->
<!--            <th>Price</th>-->
<!--        </tr>-->
<!--    </thread>-->
<!--    <tbody>-->
<!--<!--        вывод книг на страницу-->
<!--<!--    TODO: разбить по страницам по 10 шт например-->
<!--    --><?php //foreach ($books as $book):?>
<!--       <tr>
    <td><?= $book->getId()?></td>
    <td><?= $book->getTitle()?></td>
    <td><?= $book->getDescription()?></td>
    <th scope="row"><?= $book->getPrice()?></th>
</tr>
<!--    --><?php //endforeach;?>
<!---->
<!--    <?php //while ($pageCount):?>
<!--        <?php //foreach ($books as $book):?>
<!--                <tr>
<!--                    <td><?//= $book->getId()?><!--</td>
<!--                    <td><?//= $book->getTitle()?><!--</td>
<!--                    <td><?//= $book->getDescription()?><!--</td>
<!--                    <th scope="row"><?//= $book->getPrice()?><!--</th>
<!--                </tr>
<!--            <?php //endforeach;?>
<!--        <?php //$pageCount--;?>
<?php //endwhile;?>
<!--<b><?php //var_dump($pageCount);?><!--</b>
<!--
    </tbody>
</table>