<h1>Advert list</h1>
<hr>
<a href="/admin/advert/edit/">
<button type = "button" class = "btn btn-primary btn-lg" style="float: right">
    ADD NEW ADVERT
</button>
</a>

<nav aria-label="Page navigation" style="text-align: center; clear: both ">
    <ul class="pagination">
        <?php foreach ($pagination as $button) :?>
            <?php if ($button->current) : ?>
                <li class = "active"><a href="?page=<?=$button->page?>"><?=$button->text?></a></li>
            <?php elseif($button->page==='...'): ?>
                <li class='disabled'><a href="#"><?=$button->text?></a></li>
            <?php elseif($button->isActive) : ?>
                <li><a href="?page=<?=$button->page?>"><?=$button->text?></a></li>
            <?php else : ?>
                <li class='disabled'><a href="#"><?=$button->text?></a></li>
            <?php endif;
        endforeach; ?>

    </ul>
</nav>

<table class="table table-striped" >
    <thread>
        <tr class="bg-warning">
            <th>
                ID
            </th>
            <th>Name</th>
            <th>Price</th>
            <th>Company</th>
            <th colspan="2" style="text-align: center">Actions</th>

        </tr>
    </thread>
    <tbody>

    <?php foreach ($adverts as $advert):?>
        <tr>
            <td ><?= $advert->getId()?></td>
            <td ><?= $advert->getName()?></td>
            <td ><?= $advert->getPrice()?></td>
            <td ><?= $advert->getCompany()?></td>

            <td style="text-align: center">
                <a href="/admin/advert/edit/<?=$advert->getId()?>">
                    <button type = "button" class = "btn">
                        Edit
                    </button>
                </a>
            </td>
            <td>
                <a href="/admin/advert/delete/<?=$advert->getId()?>">
                    <button type = "button" class = "btn delete">
                        Delete
                    </button>
                </a>
            </td>
        </tr>
    <?php endforeach;?>
    </tbody>
</table>

