<h1>Category list</h1>
<hr>
<a href="/admin/category/edit/">
<button type = "button" class = "btn btn-primary btn-lg" style="float: right">
    ADD NEW CATEGORY
</button>
</a>

<nav aria-label="Page navigation" style="text-align: center; clear: both ">
    <ul class="pagination">
        <?php foreach ($pagination as $button) :?>
            <?php if ($button->current) : ?>
                <li class = "active"><a href="?page=<?=$button->page?>"><?=$button->text?></a></li>
            <?php elseif($button->page==='...'): ?>
                <li class='disabled'><a href="#"><?=$button->text?></a></li>
            <?php elseif($button->isActive) : ?>
                <li><a href="?page=<?=$button->page?>"><?=$button->text?></a></li>
            <?php else : ?>
                <li class='disabled'><a href="#"><?=$button->text?></a></li>
            <?php endif;
        endforeach; ?>

    </ul>
</nav>

<table class="table table-striped" >
    <thread>
        <tr class="bg-warning">
            <th>
                ID
            </th>
            <th>Name</th>
            <th colspan="2" style="text-align: center">Actions</th>

        </tr>
    </thread>
    <tbody>

    <?php foreach ($categories as $category):?>
        <tr>
            <td class="bookId"><?= $category->getId()?></td>
            <td class="title"><?= $category->getName()?></td>

            <td style="text-align: center">
                <a href="/admin/category/edit/<?=$category->getId()?>">
                    <button type = "button" class = "btn">
                        Edit
                    </button>
                </a>
            </td>
            <td>
                <a href="/admin/category/delete/<?=$category->getId()?>">
                    <button type = "button" class = "btn delete">
                        Delete
                    </button>
                </a>
            </td>
        </tr>
    <?php endforeach;?>
    </tbody>
</table>

