
<h1>Все комментарии от <?=$user->getEmail()?></h1>

<?php foreach ($comments as $comment): ?>
<div class="well">
    <div class="page">
        <h4> Дата <small><?= $comment->getDate(); ?></small></h4>
    </div>
    <div class="page-body" id="main-comment-<?=$comment->getId(); ?>" style="padding: 15px; background-color: #fff">
        <?=$comment->getMessage(); ?>
    </div>
    <div class="page">
        <p>Рейтинг: <span id="mark-<?=$comment->getId(); ?>"><?= $comment->getMark(); ?></span></p>
    </div>
</div>
<?php endforeach; ?>

<nav aria-label="Page navigation" style="text-align: center">
    <ul class="pagination">
        <?php foreach ($pagination as $button) :?>
            <?php if ($button->current) : ?>
                <li class = "active"><a href="?page=<?=$button->page?>"><?=$button->text?></a></li>
            <?php elseif($button->page==='...'): ?>
                <li class='disabled'><a href="#"><?=$button->text?></a></li>
            <?php elseif($button->isActive) : ?>
                <li><a href="?page=<?=$button->page?>"><?=$button->text?></a></li>
            <?php else : ?>
                <li class='disabled'><a href="#"><?=$button->text?></a></li>
            <?php endif;
        endforeach; ?>

    </ul>
</nav>
