<h1>My cart</h1>
<hr>

<!--<?php foreach ($books as $book): ?>-->
<!--<?=$book->getId();?><?=$book->getTitle();?>  <br>-->
<!--    <?=$book->getId();?><?=$book->getTitle();?> : <?=$cart->{$book->getId()}?>  <br>-->
<!--<?php endforeach;?>-->

<input type='hidden' value="<?=$this->getCartJson()?>" >

<ul class="list-group" id='cart-list'>
    <?php foreach ($books as $book): ?>
        <li class="list-group-item text-left">
            Book #<?=$book->getId();?>: <b><?=$book->getTitle();?></b> :
            <input type='number' min='0' id='cart-item-<?=$book->getId();?>' value="<?=$cart->{$book->getId()}?>">
            &times; <span id='price-<?=$book->getId()?>'><?=$book->getPrice()?></span> = <span id='result-<?=$book->getId()?>'></span>
        </li>

    <?php endforeach; ?>
    <li class="list-group-item text-right">Total: <span id='total'></span></li>

</ul>
<button type='button' class="btn btn-default" id="save-cart">Save</button>
<a href="#" class="btn btn-info">Checkout</a>
