<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/img/favicon.ico">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

    <title><?=$this->getTitle()?></title>

    <!-- Bootstrap core CSS -->
    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/css/style.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <script src="/js/script.js"></script>


</head>

<body style="background-color: <?=$bcolor?>">
<?php //dump($this);?>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">News Project</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">

            <ul class="nav navbar-nav">
                <li class="active"><a href="/">Новости</a></li>
                <li class="active"><a href="/analitics">Аналитика</a></li>
                <li class="active"><a href="/search">Поиск</a></li>

                <li class="menu-item dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Навигация <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Меню</a></li>
                        <li><a href="#">Меню</a></li>
                        <li class="menu-item dropdown dropdown-submenu"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Меню</a>
                            <ul class="dropdown-menu">
                                <li class="menu-item "><a href="#">Подменю</a></li>
                                <li class="menu-item "><a href="#">Подменю</a></li>
                                <li class="menu-item dropdown dropdown-submenu"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Подменю </a>
                                    <ul class="dropdown-menu">
                                        <li><a href="#">Подменю в квадрате</a></li>
                                        <li><a href="#">Подменю в квадрате</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="post" name="form" onsubmit="return false;">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Поиск" id="search" name="search">
                </div>
            </form>
            <div id="resSearch"></div>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="/register">Register</a></li>
                <?php if (!\Library\Session::has('user')) : ?>
                    <li><a href="/login">Login</a></li>
                <?php else: ?>
                    <li><a href="/logout">Logout</a></li>
                <?php endif?>

            </ul>

        </div>
    </div>
</nav>

<div class="col-md-2 col-fix pull-left" style="margin-top: 50px">
    <?php $i=0;?>
    <?php foreach ($this->getAdvert() as $advert):?>
            <?php  if ($i<4):?>
    <div class="well" id="link-<?php echo $advert->getId();?>" data-toggle="tooltip" data-placement="right" title="Купон на скидку  - <?=uniqid()?> - примените и получите скидку 10%">
        <p><?php echo $advert->getCompany()?></p>
        <p><?php echo $advert->getName()?></p>
        <p id="price-<?php echo $advert->getId();?>">Цена:</p>
        <span id="ad-<?php echo $advert->getId();?>"><?php echo $advert->getPrice();?></span> грн.<br>

    </div>
            <?php $i++; endif;?>
        <?php endforeach;?>

</div>

<div class="col-md-2 col-fix pull-right" style="margin-top: 50px">
    <?php for ($i=4; $i<8; $i++):?>
         <div class="well" id="link-<?php echo $this->getAdvert()[$i]->getId();?>" data-toggle="tooltip" data-placement="left" title="Купон на скидку  - <?=uniqid()?> - примените и получите скидку 10%">
             <p><?php echo $this->getAdvert()[$i]->getCompany()?></p>
             <p><?php echo $this->getAdvert()[$i]->getName()?></p>
             <p id="price-<?php echo $this->getAdvert()[$i]->getId();?>">Цена:</p>
             <span id="ad-<?php echo $this->getAdvert()[$i]->getId();?>"><?php echo $this->getAdvert()[$i]->getPrice();?></span> грн.<br>
            </div>
    <?php endfor;?>

</div>

<div class="container col-md-8 pull-center" style="margin-top: 50px">
    <div class="starte4-template">
        <?php if(\Library\Session::has(\Library\Session::FLASH_KEY)):?>
        <div class="alert alert-info">
            <?=\Library\Session::getFlash()?>
        </div>
        <?php endif;?>
        <?=$content?>

    </div>
</div>

<!--подписка на раccылку-->
<div id="myModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header"><button class="close" type="button" data-dismiss="modal">×</button>
                <h4 class="modal-title">Желаете подписаться на новострую рассылку?</h4>
            </div>
            <div class="modal-body">
                <input name="email" type="email" id="inputEmail" class="form-control" placeholder="Email address" >
                <input name="name" type="text" id="inputName" class="form-control" placeholder="Name">
            </div>


            <div class="modal-footer"><button class="btn btn-default" type="button" data-dismiss="modal">Отправить</button></div>
        </div>
    </div>
</div>

<div id="myModal2" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header"><button class="close" type="button" data-dismiss="modal">×</button>
                <h4 class="modal-title">Желаете подписаться на новострую рассылку?</h4>
            </div>
            <div class="modal-body">
                <input name="email" type="email" id="inputEmail" class="form-control" placeholder="Email address" >
                <input name="name" type="text" id="inputName" class="form-control" placeholder="Name">
            </div>


            <div class="modal-footer"><button class="btn btn-default" type="button" data-dismiss="modal">Отправить</button></div>
        </div>
    </div>
</div>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script>
    $('ul.dropdown-menu [data-toggle=dropdown]').on('click', function(event) {
        event.preventDefault();
        event.stopPropagation();
        $(this).parent().addClass('open');
        var menu = $(this).parent().find("ul");
        var menupos = menu.offset();
        if ((menupos.left + menu.width()) + 30 > $(window).width()) {
            var newpos = - menu.width();
        } else {
            var newpos = $(this).parent().width();
        }
        menu.css({ left:newpos });
    });
</script>



<script src="/js/bootstrap.min.js"></script>
<script src="/js/jquery.cookie.min.js"></script>

</body>
</html>

