
<h1>Изменить цвет</h1>

<h3>Меняем цвет  фона сайта</h3>

<div class="alert-box"></div>

<div id="white" class="colorB"></div>
<div id="red" class="colorB"></div>
<div id="green" class="colorB"></div>
<div id="orange" class="colorB" ></div>
<div id="yellow" class="colorB" ></div>
<div id="blue" class="colorB" ></div>
<div id="lightblue" class="colorB" ></div>
<div id="purple" class="colorB" ></div>
