<h1>Register</h1>

<div class="alert-box"></div>

<div class="container col-md-8 pull-center">
<form method='post' class="form-signin" id="register-form">
    Email address:
    <input type="email" name="email" value="<?=$form->email?>"class="form-control" required placeholder="Email address"  autofocus=""/><br>
    Password:
    <input type="password" name="password" class="form-control" placeholder="Password"/><br>
    Repeat password:
    <input type="password" name="repeatPassword" class="form-control" placeholder="Password"/><br>
    <button class="btn btn-success">Go</button><br>
</form>
</div>

