<h1>Contact me</h1>

<form method="post">
    Username: <input id='username'  class="form-control" type="text" name="username" value="<?=$form->username?>"><br>
    Email: <input id='email' class="form-control" type="email" name="email" value="<?=$form->email?>"><br>
    <textarea  id='message' class="form-control" name="message"><?=$form->message?></textarea><br>
    <button class="btn btn-success">Go</button>
</form>